### ISSUE TITLE
running this utility on startup?

### ISSUE THREAD

**Issue by melon-pi** [jadahl/gnome-monitor-config#5]
Hello, this is probably not directly related to the project (which works flawlessly btw, exactly what I needed), I am trying to run it at system startup to change the resolution after login. If I only have a single 1024x600 display connected, system starts it up with a wrong display mode and I get no output, which is what I need your utility for, but I can't get it to work on startup, only in terminal window or as a bash script and I think its because it has to run in the display environment, while usual methods like crontab run independent of it.

I was wondering if you tried to do something like that or if there's a way to use this utility to change the (preferred) video mode as it is listed, that would solve my issues too.

**Comment by melon-pi** [comment]
okay I figured out that I should start it with the .profile file on my specific install and it works! if you read this and there is a way to change the (preferred) display mode using this utility please let me know!

**Comment by jadahl** [comment]
The intended way is not to run this on startup, as everything it can do can be made to be stored permanently in the configuration file. Running it on startup means you end up with a glitchy experience because

 1. First gnome-shell launches, and creates a configuration
 2. Later the script runs, and overrides the used configuration

Between 1 and 2 there might have been frames drawn on screen, meaning you'll first get something, then suddenly things start to blink, then only after that you get what you want.

**Comment by 1player** [comment]
How do you store it in the configuration file? The configuration resets every time I suspend/restore from sleep. The only way to persist is to use the GNOME Control Center.

I just want GNOME to keep the last configuration I set with this tool.
